server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: fraud
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/fraud
    password: 'postgres'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop # just use for test to clean data when restart. Default use update
    show-sql: 'true'
  zipkin:
    base-url: http://localhost:9411