server:
  port: 8761

spring:
#  main:
#    allow-bean-definition-overriding: true
  application:
    name: eureka-server

eureka:
#  dashboard:
#    path: /dashboard
#  instance:
#    hostname: localhost
  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
    fetch-registry: false
    register-with-eureka: false
